### ISSUE TITLE
Would you consider implementing encoding and decoding for u128?

### ISSUE THREAD

**Issue by ararunaufc** [archer884/harsh#20]
I'm thinking about using this crate to provide hashids for the webserver I'm building, but my database is storing identifiers as UUIDs, which can only be reliably represented by u128.

This being said, I would like to ask if you would consider accepting u128 as input for encoding and decoding. If acceptable, I'm willing to try and propose an implementation.

**Comment by archer884** [comment]
Before I answer, I feel like I ought to ask this: have you thought about just encoding two u64 values instead? Admittedly, I'm mostly asking that because I'm curious whether it would work. I suppose I could try that myself right quick.

Anyway, I don't see why not. Let me know what you've got in mind. :)

**Comment by archer884** [comment]
Just leaving this here for future reference, in case anyone wants it for anything:
```rust
use uuid::Uuid;

fn main() {
    let id_a = dbg!(Uuid::new_v4());
    let (x, y) = dbg!(to_integers(&id_a));
    let bytes = to_bytes(x, y);
    let id_b = dbg!(Uuid::from_bytes(bytes));
    assert_eq!(id_a, id_b);
}

fn to_integers(id: &Uuid) -> (u64, u64) {
    let bytes = id.as_bytes();
    let mut left = [0u8; 8];
    let mut right = [0u8; 8];

    copy_bytes(&bytes[..8], &mut left);
    copy_bytes(&bytes[8..], &mut right);

    (u64::from_be_bytes(left), u64::from_be_bytes(right))
}

fn to_bytes(left: u64, right: u64) -> [u8; 16] {
    let mut bytes = [0u8; 16];
    copy_bytes(&left.to_be_bytes(), &mut bytes[..8]);
    copy_bytes(&right.to_be_bytes(), &mut bytes[8..]);
    bytes
}

fn copy_bytes(from: &[u8], to: &mut [u8]) {
    let pairs = from.iter().zip(to.iter_mut());
    for (from, to) in pairs {
        *to = *from;
    }
}
```

**Comment by ararunaufc** [comment]
> Before I answer, I feel like I ought to ask this: have you thought about just encoding two u64 values instead? Admittedly, I'm mostly asking that because I'm curious whether it would work. I suppose I could try that myself right quick.
> 
> Anyway, I don't see why not. Let me know what you've got in mind. :)

No, I hadn't considered this solution, but I guess it kinda meets my use case. I'll try to encode your proposal with the type system so it feels more ergonomic. For now, I'll close this issue.

Thank you.

**Comment by archer884** [comment]
@ararunaufc, if that turns out to be too annoying, I'd be happy to discuss other plans. Thanks for opening this discussion. :)
