### ISSUE TITLE
`HarshBuilder` is not exported from the crate root

### ISSUE THREAD

**Issue by abonander** [archer884/harsh#21]
This means you can't access its docs; the link to the return type of `Harsh::builder()` is white and the link to `HarshBuilder` in the crate root docs 404's.

**Comment by archer884** [comment]
Huh. That's weird. Should be fixed now. Er... I also took the opportunity to change some of the type names to be more in line with what I perceive as convention.

**Comment by abonander** [comment]
Wow, thanks for the quick response!

**Comment by archer884** [comment]
No problem. Hope that helps!
